---
# tasks file for mariadb

- name: Install MariaDB Server
  apt:
    name: mariadb-server
    state: present

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
...
