---
- name: Install Python3 pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Install PyMySQL via apt
  apt:
    name: python3-pymysql
    state: present
  become: yes

- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  become: yes

- name: Start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: Secure MariaDB installation
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  become: yes
  ignore_errors: yes  # Initial run might fail if no password is set yet

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes

- name: Create application database
  mysql_db:
    name: "{{ mariadb_database_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes

- name: Create application user
  mysql_user:
    name: "{{ mariadb_app_user }}"
    password: "{{ mariadb_app_password }}"
    priv: "{{ mariadb_database_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes

- name: Allow external connections (optional, for Angular app)
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  become: yes
  notify: Restart MariaDB

- name: Copy seed data (optional)
  copy:
    src: seed.sql
    dest: /tmp/seed.sql
  when: seed_data_file is defined
  become: yes

- name: Import seed data (optional)
  mysql_db:
    name: "{{ mariadb_database_name }}"
    state: import
    target: /tmp/seed.sql
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  when: seed_data_file is defined
  become: yes
...
