---
- name: Configure All Servers
  hosts: all
  become: yes
  roles:
    - role: ansible-playbooks/roles/jenkins
    - role: ansible-playbooks/roles/angular
    - role: ansible-playbooks/roles/mariadb
...
